<?php
    $rosFieldLabels = array("ros_id",
    'appointment_id',
    'comments',
    'rashes',
    'itching',
    'hair/nails',
    'headaches',
    'headinjury',
    'glasses',
    'change in vision',
    'eye pain',
    'double vision',
    'light flashes',
    'glaucoma',
    'last eye exam',
    'hearing change',
    'ear pain',
    'ear discharge',
    'ringing',
    'dizziness',
    'nose bleed',
    'stuffiness',
    'frequent colds',
    'hives',
    'swelling lips',
    'hay fever',
    'asthma',
    'eczema',
    'sensitive to drugs, food, pollen, or dander',
    'bleeding gums',
    'sore tongue',
    'sore throat',
    'hoarseness',
    'lumps',
    'swollen glands',
    'goiter',
    'neck stiffness',
    'breast lumps',
    'breast pain',
    'nipple discharge',
    'BSE',
    'shortness of breath',
    'cough',
    'phlem',
    'wheezing',
    'choughing blood',
    'chest pain',
    'fever',
    'night sweats',
    'swelling hands',
    'blue toes',
    'high blood pressure',
    'skipping heart beat',
    'heart murmur',
    'HX of heart medication',
    'bronchitis',
    'rheumatic heart disease',
    'appetite',
    'swallowing',
    'nausea',
    'heartburn',
    'vomiting',
    'vomiting blood',
    'constipation',
    'diarrhea',
    'bowels',
    'abdominal pain',
    'burping',
    'farting',
    'yellow skin',
    'food intolerance',
    'rectal bleed',
    'unination',
    'urine pain',
    'frequent urination',
    'urgent urination',
    'incontinence',
    'dribble',
    'urine strea',
    'bloody urine',
    'uti stones',
    'leg cramps',
    'varicose veins',
    'clots in vein',
    'muscle pain',
    'muscle swelling',
    'muscle stiffness',
    'joint motion',
    'broken bone',
    'sprain',
    'arthritis',
    'gout', 
    'seizures',
    'fainting',
    'paralysis',
    'weakness',
    'muscle size',
    'muscle spasms',
    'tremor',
    'involuntary move',
    'incoordination',
    'numbness',
    'pins and needles',
    'anemia',
    'bruising and bleed',
    'transfusions',
    'growth',
    'appetite',
    'thirst',
    'increased urination',
    'thyroid',
    'head cold',
    'sweating',
    'diabetes',
    'anxiety',
    'depression',
    'memory',
    'unusual problems',
    'sleep',
    'psychiatrist',
    'mood');
?>